name: Run tests

on: [push]

jobs:
    run-tests:
        name: Run tests
        runs-on: ubuntu-latest
        services:
            mariadb:
                image: mariadb:10.4.12-bionic
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: true
                    MYSQL_DATABASE: rizkhal-testing
                    MYSQL_USER: rizkhal
                    MYSQL_PASSWORD: rizkhal
                ports:
                    - 33060:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
        steps:
            -   uses: actions/checkout@v1

            -   name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: '7.4'
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                    coverage: none

            -   name: Cache dependencies
                uses: actions/cache@v1
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.lock') }}

            -   name: Run composer install
                run: composer update --${{ matrix.dependency }} --prefer-dist --no-interaction --no-suggest --no-progress

            -   name: Prepare Laravel Application
                run: |
                    cp .env.example .env
                    php artisan key:generate

            -   name: Run tests
                run: ./vendor/bin/phpunit
                env:
                  DB_PORT: ${{ job.services.mariadb.ports[3306] }}
                  DB_DATABASE: rizkhal-testing
                  DB_USERNAME: rizkhal
                  DB_PASSWORD: rizkhal
